### ISSUE TITLE
list of available hashes

### ISSUE THREAD

**Issue by MareoRaft** [cupen/checksum-cli#1]
Would you be willing to add the list of acceptable hash types to the output of 

    checksum --help

?  Alternatively, I can try to do it myself and create a pull request.  Let me know, thanks!

**Comment by cupen** [comment]
@MareoRaft  Thanks for your feedback, it's done.

**Comment by cupen** [comment]
help infomation.
```
usage: checksum [-h] [--hash hash] file

Generate the checksum of a file.

positional arguments:
  file         file path

optional arguments:
  -h, --help   show this help message and exit
  --hash hash  hash name. supports: blake2b, blake2s, md5, sha1, sha224,
               sha256, sha384, sha3_224, sha3_256, sha3_384, sha3_512, sha512
```

@MareoRaft Feel free to send me a pull request if you need something else.

**Comment by MareoRaft** [comment]
Thank you kindly!
